### ISSUE TITLE
could not import from 'material-ui', must use 'material-ui/index' instead

### ISSUE THREAD

**Issue by mattiamanzati** [mattiamanzati/typings-material-ui#1]
**TypeScript Version:**  2.0.0

**Typeings Version:** master  

**Code**

``` ts
// this will throw error
import {AppBar} from 'material-ui'

// this works fine
import {AppBar} from 'material-ui/index'

```

**Expected behavior:**
"/index" should not be necessary; is there any config to perform with the typings.json file? Unfortunately I don't know how to solve it atm.

**Actual behavior:** 
"/index" is required, "material-ui" seems to be not declared.

**Comment by alitaheri** [comment]
I've had this issue with typings before. It fails to resolve index when bundling. type adding `main: index.d.ts` to typings.json not sure if it will be fixed, if not then try renaming to main.d.ts with `main: main.dts` in typings.json.

**Comment by mattiamanzati** [comment]
Yeah, that was the gist! Fixed!
