### ISSUE TITLE
should we generate icons files via script?

### ISSUE THREAD

**Issue by mattiamanzati** [mattiamanzati/typings-material-ui#2]
**TypeScript Version:** 2.0.0

**Typeings Version:** master  

**Issue:**
material-ui has a lot of svg icons files; is there a way to declare them all at once, or should we consider using a script to generate them in a batch process?

**Comment by alitaheri** [comment]
We should absolutely generate the typings. We can use reuse the [icon-builder](https://github.com/callemall/material-ui/tree/master/packages/icon-builder) itself :grin: Leave this one to me :sunglasses:

**Comment by mattiamanzati** [comment]
Sure! Feel free to give it a shot! :sunglasses:

**Comment by alitaheri** [comment]
On it, Thanks for the invite :blush:
