### ISSUE TITLE
Autocomplete dataSource typings too narrow, dataSourceConfig missing.

### ISSUE THREAD

**Issue by neopostmodern** [mattiamanzati/typings-material-ui#20]
**TypeScript Version:** 2.0.2

**Typings Version:** master  

**Issue:**
Autocomplete `dataSource` typings are too narrow. They ignore the existence of dataSourceConfig (which is missing).

**Code:**

``` tsx
const countries = [
  { "name": "Afghanistan", "code": "AF" },
  { "name": "Åland Islands", "code": "AX" },
  { "name": "Albania", "code": "AL" }
];
let autocomplete = <AutoComplete floatingLabelText="Search for a country"
                         filter={AutoComplete.fuzzyFilter}
                         dataSource={countries}
                         dataSourceConfig={{ text: 'name', value: 'code' }} />
```

See the [doc](http://www.material-ui.com/#/components/auto-complete).

**Comment by mattiamanzati** [comment]
Thanks for your awesome feedback!

It should be fixed now, try installing `typings install github:mattiamanzati/typings-material-ui` and let me know!

Mattia.

**Comment by neopostmodern** [comment]
Yup, seems to work.
