### ISSUE TITLE
(Undocumented) property "label" is missing on RadioButton

### ISSUE THREAD

**Issue by neopostmodern** [mattiamanzati/typings-material-ui#21]
**TypeScript Version:** 2.0.2

**Typings Version:** master  

**Issue:**
Error:

```
error TS2339: Property 'label' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<RadioButton> & RadioButtonProps & { children?: Rea...'.
```

It's **not documented** but appears in the example code (and works flawlessly), see [docs](http://www.material-ui.com/#/components/radio-button)

**Code:**

``` ts
<RadioButton label="Label!" value="value" />
```

**Comment by mattiamanzati** [comment]
It should be fixed now, try installing `typings install github:mattiamanzati/typings-material-ui` and let me know!
