### ISSUE TITLE
typings progress tracking

### ISSUE THREAD

**Issue by mattiamanzati** [mattiamanzati/typings-material-ui#3]
**TypeScript Version:** 2.0.0

**Typings Version:** master  

**Issue**
This issue will and tracks the current status of the typings! Feel free to comment to assign yourself to one of the missing components or report missing ones!
- [X] AppBar
- [X] AutoComplete
- [X] Avatar
- [x] Badge
- [x] Card
- [x] Checkbox (@mattiamanzati)
- [x] CircularProgress (@alitaheri #14)
- [x] DatePicker (@alitaheri #11)
- [x] Dialog (@alitaheri #12)
- [X] Divider
- [x] Drawer (@alitaheri #13)
- [x] DropDownMenu (@alitaheri #15)
- [x] FlatButton
- [x] FloatingActionButton
- [x] FontIcon (@alitaheri #16)
- [x] GridList (@alitaheri #17)
- [X] IconButton
- [X] IconMenu
- [X] Menu
- [X] MenuItem
- [x] LinearProgress (@alitaheri #14)
- [x] List (@alitaheri #18)
- [x] Paper (@mattiamanzati)
- [x] Popover (@alitaheri #19)
- [x] RadioButton (@mattiamanzati)
- [x] RaisedButton
- [x] RefreshIndicator (@alitaheri #14)
- [x] SelectField (@alitaheri #19)
- [x] Slider (@alitaheri #19)
- [x] Snackbar (@alitaheri #19)
- [x] Stepper (@mattiamanzati)
- [x] Subheader (@alitaheri #19)
- [X] SvgIcon
- [x] Table (@alitaheri #19)
- [x] Tabs (@alitaheri #6)
- [x] TextField (@alitaheri #11)
- [x] TimePicker (@alitaheri #11)
- [x] Toggle (@alitaheri #10)
- [x] Toolbar (@alitaheri #7)

**Comment by alitaheri** [comment]
@mattiamanzati After you review and agree with the changes, just give the go I'll resolve conflicts and merge myself. I need your review, so i won't just merge PRs myself :grin:

**Comment by alitaheri** [comment]
It's Done :tada: :tada:

**Comment by mattiamanzati** [comment]
I'll gonna submit a PR to the typings registry! :D

**Comment by mattiamanzati** [comment]
So people can start using it and we will have feedbacks!

**Comment by alitaheri** [comment]
Yeah, that would be great :+1: :+1: :grin:
