### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by alitaheri** [mattiamanzati/typings-material-ui#8]
I think this project is big enough to enable linting. Do you agree? Should I set up `tslint` with some rules?

If so we should agree on some rules :sweat_smile: 
1. semicolon ( always or never ) [ ]
2. new line at the end of each file ( yes or no ) [ ]
3. indentation ( 2 or 4 ) [ ]

**Comment by mattiamanzati** [comment]
Sure! Linting would only be a good thing!

My usual setup:
1. no semicolons
2. yes, new line at end
3. 4 spaces for indentation

**Comment by alitaheri** [comment]
mine is:
1. semicolon
2. yes
3. 2 spaces

But I don't really care, as long as it's consistent :+1: We'll go with your preference :+1: :+1:

**Comment by mattiamanzati** [comment]
No problem; have a shot with what you like most :)

**Comment by alitaheri** [comment]
I'll do it when all the components are added to make sure it won't interfere. Besides there are other things that must be done to improve quality. So I'll just do it all at once when the main work is finished :grin:
